### ISSUE TITLE
No module named api.blueprint_api

### ISSUE THREAD

**Issue by boyska** [insomnia-lab/libreant#165]
That's what running `webant` produces on commit g2ffa1f7. It happens both on my local machine and on our "CI" machine.

```
Traceback (most recent call last):
  File "/libreant/g2ffa1f7ecabd567ff08fd715507092ce48f32d70/ve/bin/webant", line 9, in <module>
    load_entry_point('libreant==0.1.3', 'console_scripts', 'webant')()
  File "/libreant/g2ffa1f7ecabd567ff08fd715507092ce48f32d70/ve/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/libreant/g2ffa1f7ecabd567ff08fd715507092ce48f32d70/ve/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/libreant/g2ffa1f7ecabd567ff08fd715507092ce48f32d70/ve/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/libreant/g2ffa1f7ecabd567ff08fd715507092ce48f32d70/ve/local/lib/python2.7/site-packages/webant/__init__.py", line 1, in <module>
    from webant import create_app
  File "/libreant/g2ffa1f7ecabd567ff08fd715507092ce48f32d70/ve/local/lib/python2.7/site-packages/webant/webant.py", line 20, in <module>
    from api.blueprint_api import api
ImportError: No module named api.blueprint_api
```

Don't know when it has been introduced.

Sorry for the poor debugging.

**Comment by boyska** [comment]
seems that 70590361f68b is a bad commit, too.

Interestingly, unit tests always pass.

**Comment by boyska** [comment]
ok, according to `git bisect` (hooray for it!) 9058e5df8a643511dcf82c14160dc034ea039698 is the first bad commit.

I'm really curious about how was anyone else able to run this while I was not.

**Comment by leonaard** [comment]
This doesn't happen if you install libreant in `develop` mode, but I
dont know the reason yet.

**Comment by ael-code** [comment]
On 06/15/2015 10:10 AM, leonaard wrote:
> This doesn't happen if you install libreant in `develop` mode, but I
> dont know the reason yet.
> 

That's true.

`api` module is not included in the installation package.

if you look at:
`<venv_path>/local/lib/python2.7/site-packages/libreant-0.1.3-py2.7.egg/webant/`
you will find that `api` folder is missing.

I can't understand how is it possible. I'll investigate.
Fuck `setuptools` again.
