### ISSUE TITLE
gevent error on debian8

### ISSUE THREAD

**Issue by g3-3k** [insomnia-lab/libreant#177]
I tried to install on a debian 8 and everything works fine (especially elasticsearch ;) ) but gevent.
Down here the log

Installed /home/bambi/libreant/ve/lib/python2.7/site-packages/libreant-0.2-py2.7.egg
Processing dependencies for libreant==0.2
Searching for gevent
Reading https://pypi.python.org/simple/gevent/
Best match: gevent 1.1a1
Downloading https://pypi.python.org/packages/source/g/gevent/gevent-1.1a1.tar.gz#md5=170c76535346f624ba9a194a4049c0bb
Processing gevent-1.1a1.tar.gz
Writing /tmp/easy_install-jH1F9r/gevent-1.1a1/setup.cfg
Running gevent-1.1a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jH1F9r/gevent-1.1a1/egg-dist-tmp-gbfmMZ
Running '/bin/sh /tmp/easy_install-jH1F9r/gevent-1.1a1/libev/configure > configure-output.txt' in /tmp/easy_install-jH1F9r/gevent-1.1a1/build/temp.linux-x86_64-2.7/libev
/tmp/easy_install-jH1F9r/gevent-1.1a1/libev/configure: line 2684: printf: write error: Broken pipe
configure: error: in `/tmp/easy_install-jH1F9r/gevent-1.1a1/build/temp.linux-x86_64-2.7/libev':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by g3-3k** [comment]
Now I ll install the c compiler and try again. In case we should considere it as a dependecy?

**Comment by g3-3k** [comment]
Installing gcc++ I solved but still it presents many error (50) on test.
Moreover if I start libreant -d it says :
2015-07-02 06:01:01,033 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": null, "ES_INDEXNAME": "libreant", "FSDB_PATH": "/tmp/libreant_fsdb"}
2015-07-02 06:01:01,034 [fsdb.fsdb] [DEBUG] Fsdb config file found. Runtime parameters will be ignored. [/tmp/libreant_fsdb/.fsdb.conf]
2015-07-02 06:01:01,035 [fsdb.fsdb] [DEBUG] Fsdb initialized successfully: {root: /tmp/libreant_fsdb, deep: 3, hash_alg: sha1, fmode: 0660, dmode: 0770}
Traceback (most recent call last):
  File "/home/bambi/libreant/ve/bin/libreant", line 9, in <module>
    load_entry_point('libreant==0.2', 'console_scripts', 'libreant')()
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/cli/libreant.py", line 43, in libreant
    main(conf)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py", line 214, in main
    app = create_app(conf)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py", line 60, in create_app
    app = LibreantViewApp("webant", conf)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py", line 51, in __init__
    super(LibreantViewApp, self).__init__(import_name, defaults)
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py", line 40, in __init__
    self.archivant = Archivant(conf={k: self.config[k] for k in ('FSDB_PATH', 'ES_HOSTS', 'ES_INDEXNAME')})
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/archivant/archivant.py", line 51, in __init__
    db.setup_db()
  File "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/libreantdb/api.py", line 141, in setup_db
    if not self.es.indices.exists(self.index_name):
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 216, in exists
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 307, in perform_request
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 85, in perform_request
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', error(111, 'Connection refused'))) caused by: ProtocolError(('Connection aborted.', error(111, 'Connection refused')))

**Comment by ael-code** [comment]
On 07/02/2015 03:01 PM, cocco->nat wrote:
> Installing gcc++ I solved but still it presents many error (50) on test.
> Moreover if I start libreant -d it says :
> 2015-07-02 06:01:01,033 [archivant] [DEBUG] initializing with this
> config: {"ES_HOSTS": null, "ES_INDEXNAME": "libreant", "FSDB_PATH":
> "/tmp/libreant_fsdb"}
> 2015-07-02 06:01:01,034 [fsdb.fsdb] [DEBUG] Fsdb config file found.
> Runtime parameters will be ignored. [/tmp/libreant_fsdb/.fsdb.conf]
> 2015-07-02 06:01:01,035 [fsdb.fsdb] [DEBUG] Fsdb initialized
> successfully: {root: /tmp/libreant_fsdb, deep: 3, hash_alg: sha1, fmode:
> 0660, dmode: 0770}
> Traceback (most recent call last):
> File "/home/bambi/libreant/ve/bin/libreant", line 9, in
> load_entry_point('libreant==0.2', 'console_scripts', 'libreant')()
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py",
> line 664, in *call*
> return self.main(/args, */kwargs)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py",
> line 644, in main
> rv = self.invoke(ctx)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py",
> line 837, in invoke
> return ctx.invoke(self.callback, */ctx.params)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py",
> line 464, in invoke
> return callback(/args, **kwargs)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/cli/libreant.py",
> line 43, in libreant
> main(conf)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py",
> line 214, in main
> app = create_app(conf)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py",
> line 60, in create_app
> app = LibreantViewApp("webant", conf)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py",
> line 51, in *init*
> super(LibreantViewApp, self).*init*(import_name, defaults)
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/webant/webant.py",
> line 40, in *init*
> self.archivant = Archivant(conf={k: self.config[k] for k in
> ('FSDB_PATH', 'ES_HOSTS', 'ES_INDEXNAME')})
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/archivant/archivant.py",
> line 51, in *init*
> db.setup_db()
> File
> "/home/bambi/libreant/ve/local/lib/python2.7/site-packages/libreant-0.2-py2.7.egg/libreantdb/api.py",
> line 141, in setup_db
> if not self.es.indices.exists(self.index_name):
> File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line
> 69, in _wrapped
> File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py",
> line 216, in exists
> File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line
> 307, in perform_request
> File
> "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py",
> line 85, in perform_request
> elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection
> aborted.', error(111, 'Connection refused'))) caused by:
> ProtocolError(('Connection aborted.', error(111, 'Connection refused')))

Seems that Elasticsearch is not listening on standard port (9200).

To ensure that Elastisearch is running:
```systemctl is-active elasticsearch.service```

To view the port on which is listening:
```sudo netstat -tpln | grep java```

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645
