### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#239]
On a brand new installation of libreant, this is happening when I try to login with admin user.

OS: Debian 8

All tests are passed.
##### Virtual environment packages
```
Babel==2.2.0
Flask==0.10.1
Flask-Authbone==0.2.1
Flask-Babel==0.9
Flask-Bootstrap==3.3.5.7
Flask-Script==2.0.5
Fsdb==0.3.3
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.3
argparse==1.2.1
click==6.2
dominate==2.1.16
elasticsearch==1.9.0
gevent==1.0.2
greenlet==0.4.9
itsdangerous==0.24
libreant==0.3
nose==1.3.7
opensearch==0.9.2
passlib==1.6.5
peewee==2.8.0
pytz==2015.7
speaklater==1.3
urllib3==1.14
visitor==0.1.2
wsgiref==0.1.2
```

##### Error log
```
Jan 01 01:32:11 dluserver libreant[1212]: Traceback (most recent call last):
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
Jan 01 01:32:11 dluserver libreant[1212]: return self.wsgi_app(environ, start_response)
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
Jan 01 01:32:11 dluserver libreant[1212]: response = self.make_response(self.handle_exception(e))
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
Jan 01 01:32:11 dluserver libreant[1212]: reraise(exc_type, exc_value, tb)
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Jan 01 01:32:11 dluserver libreant[1212]: response = self.full_dispatch_request()
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
Jan 01 01:32:11 dluserver libreant[1212]: response = self.process_response(response)
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
Jan 01 01:32:11 dluserver libreant[1212]: self.save_session(ctx.session, response)
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
Jan 01 01:32:11 dluserver libreant[1212]: return self.session_interface.save_session(self, session, response)
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/flask/sessions.py", line 326, in save_session
Jan 01 01:32:11 dluserver libreant[1212]: val = self.get_signing_serializer(app).dumps(dict(session))
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/itsdangerous.py", line 566, in dumps
Jan 01 01:32:11 dluserver libreant[1212]: rv = self.make_signer(salt).sign(payload)
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/itsdangerous.py", line 409, in sign
Jan 01 01:32:11 dluserver libreant[1212]: timestamp = base64_encode(int_to_bytes(self.get_timestamp()))
Jan 01 01:32:11 dluserver libreant[1212]: File "/opt/libreant/ve/lib/python2.7/site-packages/itsdangerous.py", line 220, in int_to_bytes
Jan 01 01:32:11 dluserver libreant[1212]: assert num >= 0
Jan 01 01:32:11 dluserver libreant[1212]: AssertionError
Jan 01 01:32:11 dluserver libreant[1212]: 10.10.10.138 - - [2002-01-01 01:32:11] "POST /login HTTP/1.1" 500 20925 0.605964
```

**Comment by boyska** [comment]
since it is an AssertionError, it won't happen when python is run with `-O` or with the enviroment variable `PYTHONOPTIMIZE=1`
Of course this doesn't sound right, but let's see what happens, maybe the stack trace will be clearer.

BTW, is that the _full_ stacktrace?

**Comment by ael-code** [comment]
I upgraded flask package into the virtual env through:
``` pip install --upgrade flask```

Seems that not even one packages was actually upgraded (no version changes)
But the issue is not present any more. :)
```
Babel==2.2.0
Flask==0.10.1
Flask-Authbone==0.2.1
Flask-Babel==0.9
Flask-Bootstrap==3.3.5.7
Flask-Script==2.0.5
Fsdb==0.3.3
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.3
argparse==1.2.1
click==6.2
dominate==2.1.16
elasticsearch==1.9.0
gevent==1.0.2
greenlet==0.4.9
itsdangerous==0.24
libreant==0.3
nose==1.3.7
opensearch==0.9.2
passlib==1.6.5
peewee==2.8.0
pytz==2015.7
speaklater==1.3
urllib3==1.14
visitor==0.1.2
wsgiref==0.1.2
```

**Comment by boyska** [comment]
so, which version of flask was buggy? which one is fine?

**Comment by ael-code** [comment]
> so, which version of flask was buggy? which one is fine?

I think that there was a problem with a dirty package installation into the ve. It seems not related to any specific version of any package.

**Comment by boyska** [comment]
ok, good
