### ISSUE TITLE
_timestamp parameter deprecated in elasticsearch 2

### ISSUE THREAD

**Issue by leophys** [insomnia-lab/libreant#264]
I got crazy trying to install libreant on a archlinux container (therefore es >=2).
I got an error related to the failed connection to elasticsearch. At last discovered that `_timestamp` parameter is now [deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html) in elasticsearch >=2.0.0-beta2

**Comment by boyska** [comment]
First of all, thanks for these insights: we have little testing with elasticsearch2 (see also #262 ) so it's great that you're doing it.

Still, something looks strange in your bug report. First of all, a deprecation does not mean that it does not work, but that it _should_ not be used anymore, and that in _some future version_ it might be removed. So everything should still work fine. Also, you are talking about failed connection. Even if `_timestamp` was actually removed from elasticsearch2, that won't be a connection error.

Could you please paste your log?

**Comment by leophys** [comment]
I can now specify that such an issue is specific to the case of a freshly installed libreant, with no elasticsearch index created yet. 
The error log is the following:

```
2016-03-10 15:30:00,596 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": "localhost:9200", "ES_INDEXNAME": "libreantest", "FSDB_PATH": "/home/leo/fsdb"}
2016-03-10 15:30:00,596 [fsdb.fsdb] [DEBUG] Fsdb config file found. Runtime paramete2016-03-10 15:30:00,596 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": "localhost:9200", "ES_INDEXNAME": "libreantest", "FSDB_PATH": "/home/leo/fsdb"}
rs will be ignored. [/home/leo/fsdb/.fsdb.conf]
2016-03-10 15:30:00,596 [fsdb.fsdb] [DEBUG] Fsdb initialized successfully: {root: /home/leo/fsdb, deep: 3, hash_alg: sha1, fmode: 0660, dmode: 0770}
2016-03-10 15:30:00,596 [users] [DEBUG] Initializing da2016-03-10 15:30:00,596 [fsdb.fsdb] [DEBUG] Fsdb config file found. Runtime parameters will be ignored. [/home/leo/fsdb/.fsdb.conf]
tabase: {'url': u'sqlite:////home/leo/users/users.db', 'pwd_rounds': 29000, 'pwd_salt_size': 16}
2016-03-10 15:30:00,596 [users] [DEBUG] Creating missing database tables
2016-03-10 15:30:00,597 [users] [DEBUG] Populating with default users
2016-03-102016-03-10 15:30:00,596 [fsdb.fsdb] [DEBUG] Fsdb initialized successfully: {root: /home/leo/fsdb, deep: 3, hash_alg: sha1, fmode: 0660, dmode: 0770}
 15:30:00,613 [werkzeug] [INFO]  * Restarting with stat
2016-03-10 15:30:00,857 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": "localhost:9200", "ES_INDEXNAME": "libreantest", "FSDB_PATH": "/home/leo/fsdb"}
2016-03-10 15:30:00,857 [fsd2016-03-10 15:30:00,596 [users] [DEBUG] Initializing database: {'url': u'sqlite:////home/leo/users/users.db', 'pwd_rounds': 29000, 'pwd_salt_size': 16}
b.fsdb] [DEBUG] Fsdb config file found. Runtime parameters will be ignored. [/home/leo/fsdb/.fsdb.conf]
2016-03-10 15:30:00,857 [fsdb.fsdb] [DEBUG] Fsdb initialized successfully: {root: /home/leo/fsdb, deep: 3, hash_alg: sha1, fmode: 0660, dmode: 0770}
22016-03-10 15:30:00,596 [users] [DEBUG] Creating missing database tables
016-03-10 15:30:00,858 [users] [DEBUG] Initializing database: {'url': u'sqlite:////home/leo/users/users.db', 'pwd_rounds': 29000, 'pwd_salt_size': 16}
2016-03-10 15:30:00,858 [users] [DEBUG] Creating missing database tables
2016-03-10 15:30:00,859 [use2016-03-10 15:30:00,597 [users] [DEBUG] Populating with default users
rs] [DEBUG] Populating with default users
2016-03-10 15:30:00,875 [werkzeug] [WARNING]  * Debugger is active!
2016-03-10 15:30:00,875 [werkzeug] [INFO]  * Debugger pin code: 241-988-494
2016-03-10 15:30:00,876 [webant] [INFO] Listening on http://0.0.2016-03-10 15:30:00,613 [werkzeug] [INFO]  * Restarting with stat
0.0:5000/
2016-03-10 15:30:03,797 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:03] "GET / HTTP/1.1" 200 2818 0.028783
/home/leo/libreant/esbug/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/filesystem.py:63: BrokenFilesystemWarning: D2016-03-10 15:30:00,857 [archivant] [DEBUG] initializing with this config: {"ES_HOSTS": "localhost:9200", "ES_INDEXNAME": "libreantest", "FSDB_PATH": "/home/leo/fsdb"}
etected a misconfigured UNIX files2016-03-10 15:30:00,857 [fsdb.fsdb] [DEBUG] Fsdb config file found. Runtime parameters will be ignored. [/home/leo/fsdb/.fsdb.conf]
ystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
  BrokenFilesystemWarning)
Traceback (most recent call last):
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __2016-03-10 15:30:00,857 [fsdb.fsdb] [DEBUG] Fsdb initialized successfully: {root: /home/leo/fsdb, deep: 3, hash_alg: sha1, fmode: 0660, dmode: 0770}
call__
    return self.wsgi_app(environ, start_response)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/2016-03-10 15:30:00,858 [users] [DEBUG] Initializing database: {'url': u'sqlite:////home/leo/users/users.db', 'pwd_rounds': 29000, 'pwd_salt_size': 16}
home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.2016-03-10 15:30:00,858 [users] [DEBUG] Creating missing database tables
py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  2016-03-10 15:30:00,859 [users] [DEBUG] Populating with default users
File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.eg2016-03-10 15:30:00,875 [werkzeug] [WARNING]  * Debugger is active!
g/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rul2016-03-10 15:30:00,875 [werkzeug] [INFO]  * Debugger pin code: 241-988-494
e.endpoint](**req.view_args)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/libreant-0.3-py2.7.egg/webant/webant.py", line 101, in search
    res = app.archivant._db.user_search(query)['hits']['hits']
  File "/home/leo/libreant/esbug/li2016-03-10 15:30:00,876 [webant] [INFO] Listening on http://0.0.0.0:5000/
b/python2.7/site-packages/libreant-0.3-py2.7.egg/archivant/archivant.py", line 61, in _db
    db.setup_db()
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/libreant-0.3-py2.7.egg/libreantdb/api.py", line 144, in setup_db
    'mappings': 2016-03-10 15:30:03,797 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:03] "GET / HTTP/1.1" 200 2818 0.028783
maps})
  File "build/bdist.linux-x86_64/egg/elas/home/leo/libreant/esbug/lib/python2.7/site-packages/Werkzeug-0.11.4-py2.7.egg/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
ticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 105, in create
    params=params, body=body)
  File "build/bdist.linux-x86_  BrokenFilesystemWarning)
64/egg/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllibTraceback (most recent call last):
3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_c  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
ode, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [_timestamp] has unsupported parameters:  [store : yes]')
2016-03-10 15:30:05,061 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:3    return self.wsgi_app(environ, start_response)
0:05] "GET /search?q=%2A%3A%2A HTTP/1.1" 500 30518 0.059725
2016-03-10 15:30:05,127 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 6348 0.000781
2016-03-10 15:30:05,130 [webant] [  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 96074 0.000520
2016-03-10 15:30:05,131 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?__debugger__=yes&cmd=resource&f=debugger.    response = self.make_response(self.handle_exception(e))
js HTTP/1.1" 200 6303 0.000407
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/libreant-0.3-py2.7.egg/webant/webant.py", line 101, in search
    res = app.archivant._db.user_search(query)['hits']['hits']
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/libreant-0.3-py2.7.egg/archivant/archivant.py", line 61, in _db
    db.setup_db()
  File "/home/leo/libreant/esbug/lib/python2.7/site-packages/libreant-0.3-py2.7.egg/libreantdb/api.py", line 144, in setup_db
    'mappings': maps})
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 105, in create
    params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [_timestamp] has unsupported parameters:  [store : yes]')
2016-03-10 15:30:05,061 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?q=%2A%3A%2A HTTP/1.1" 500 30518 0.059725
2016-03-10 15:30:05,127 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 6348 0.000781
2016-03-10 15:30:05,130 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 96074 0.000520
2016-03-10 15:30:05,131 [webant] [INFO] 10.0.0.1 - - [2016-03-10 15:30:05] "GET /search?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 6303 0.000407

```

**Comment by boyska** [comment]
Ok, so the problem is with `_timestamp.store = yes`

**Comment by boyska** [comment]
@leophys does the test suite work for you? I would be seriously surprised if you got this error but the unit tests worked. I expect that most of the unit tests will fail.

```sh
NOSE_WHERE=libreantdb python setup.py test
```

should be enough

**Comment by leophys** [comment]
Same traceback

```
% NOSE_WHERE=libreantdb python setup.py test
running test
Searching for coverage
Best match: coverage 4.1b2
Processing coverage-4.1b2-py2.7-linux-x86_64.egg

Using /home/leo/libreant/.eggs/coverage-4.1b2-py2.7-linux-x86_64.egg
Searching for nose
Best match: nose 1.3.7
Processing nose-1.3.7-py2.7.egg

Using /home/leo/libreant/.eggs/nose-1.3.7-py2.7.egg
running egg_info
writing requirements to libreant.egg-info/requires.txt
writing libreant.egg-info/PKG-INFO
writing top-level names to libreant.egg-info/top_level.txt
writing dependency_links to libreant.egg-info/dependency_links.txt
writing entry points to libreant.egg-info/entry_points.txt
reading manifest file 'libreant.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'libreant.egg-info/SOURCES.txt'
running build_ext
E
======================================================================
ERROR: test suite for <module 'libreantdb.test' from '/home/leo/libreant/libreantdb/test/__init__.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leo/libreant/.eggs/nose-1.3.7-py2.7.egg/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/leo/libreant/.eggs/nose-1.3.7-py2.7.egg/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/leo/libreant/.eggs/nose-1.3.7-py2.7.egg/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/leo/libreant/.eggs/nose-1.3.7-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/home/leo/libreant/libreantdb/test/__init__.py", line 10, in setUpPackage
    db.setup_db()
  File "/home/leo/libreant/libreantdb/api.py", line 144, in setup_db
    'mappings': maps})
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 105, in create
    params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'Mapping definition for [_timestamp] has unsupported parameters:  [store : yes]')
-------------------- >> begin captured logging << --------------------
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: "HEAD /test-book HTTP/1.1" 404 0
elasticsearch: WARNING: HEAD /test-book [status:404 request:0.003s]
elasticsearch: DEBUG: > None
elasticsearch: DEBUG: < 
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "PUT /test-book HTTP/1.1" 400 459
elasticsearch: WARNING: PUT /test-book [status:400 request:0.013s]
elasticsearch: DEBUG: > {"mappings": {"book": {"_timestamp": {"enabled": "true", "store": "yes"}, "properties": {"_text_it": {"type": "string", "analyzer": "it_analyzer"}, "_text_en": {"type": "string", "analyzer": "english"}}}}, "settings": {"analysis": {"filter": {"italian_elision": {"articles": ["c", "l", "all", "dall", "dell", "nell", "sull", "coll", "pell", "gl", "agl", "dagl", "degl", "negl", "sugl", "un", "m", "t", "s", "v", "d"], "type": "elision"}, "italian_stop": {"stopwords": "_italian_", "type": "stop"}, "italian_stemmer": {"type": "stemmer", "language": "italian"}}, "analyzer": {"it_analyzer": {"filter": ["italian_elision", "lowercase", "italian_stop", "italian_stemmer"], "type": "custom", "tokenizer": "standard"}}}}}
elasticsearch: DEBUG: < {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [_timestamp] has unsupported parameters:  [store : yes]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [book]: Mapping definition for [_timestamp] has unsupported parameters:  [store : yes]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [_timestamp] has unsupported parameters:  [store : yes]"}},"status":400}
--------------------- >> end captured logging << ---------------------

Name                Stmts   Miss  Cover   Missing
-------------------------------------------------
libreantdb.py           2      0   100%
libreantdb/api.py     107     70    35%   15-27, 31-44, 145-148, 153, 156, 159, 169-177, 180, 183, 186-189, 192, 195, 200, 203, 206, 209-210, 217, 223-224, 227, 237-240, 243, 257-262, 275-280, 286-296
-------------------------------------------------
TOTAL                 109     70    36%
----------------------------------------------------------------------
Ran 0 tests in 0.020s

FAILED (errors=1)

```

**Comment by boyska** [comment]
@leophys I might have fixed it in this branch https://github.com/boyska/libreant/tree/264-dont-store-timestamp-es could you please test it?
Even if it works, I **will not** propose such a PR before the sprint we're doing to release libreant with the volume editing feature works is completed. Indeed in that commit I am changing some internal, and I'm not even sure it's the correct way of fixing this bug.

**Comment by leophys** [comment]
@boyska I confirm it works. I assumed i had to repeat the manual patching as before.
Anyway many tests fail with issues related to elasticsearch (but I assume this is due because the test suite is not made for elasticsearch 2).

Can you suggest something specific I should test in this phase to help the release?

**Comment by boyska** [comment]
the **full** test suite should be enough. If it is not enough, we have bigger problems

```sh
python setup.py test
```

**Comment by leophys** [comment]
```
-------------------- >> begin captured logging << --------------------
archivant: DEBUG: initializing with this config: {"ES_HOSTS": null, "ES_INDEXNAME": "test-archivant", "FSDB_PATH": "/tmp/archivant_test_UEAHGa"}
fsdb.fsdb: DEBUG: Fsdb initialized successfully: {root: /tmp/archivant_test_UEAHGa, deep: 3, hash_alg: sha1, fmode: 0660, dmode: 0770}
archivant: DEBUG: adding new volume:
	data: {'_language': 'en', 'key2': {'key22': 'value22', 'key21': 'value21'}, 'key1': 'value1', 'key3': [1, 2, 3]}
	files: [{'file': '/tmp/archivant_test_UEAHGa/tmpTiOLae'}, {'file': '/tmp/archivant_test_UEAHGa/tmp7u9N1R'}, {'file': '/tmp/archivant_test_UEAHGa/tmpgoLIts'}]
fsdb.fsdb: DEBUG: Added file: "72ceb09f552b40aeb7f4d80c6e6f96cf3ea60869" [ /tmp/archivant_test_UEAHGa/72/ceb0/9f552b40/aeb7f4d80c6e6f96cf3ea60869 ]
fsdb.fsdb: DEBUG: Added file: "27bc5fea5207e3cac9b42e043433be4161a2beb0" [ /tmp/archivant_test_UEAHGa/27/bc5f/ea5207e3/cac9b42e043433be4161a2beb0 ]
fsdb.fsdb: DEBUG: Added file: "188b8b605504ed744a7e42060382e518765b67f2" [ /tmp/archivant_test_UEAHGa/18/8b8b/605504ed/744a7e42060382e518765b67f2 ]
archivant: DEBUG: constructed volume for insertion: {'_language': 'en', 'key2': {'key22': 'value22', 'key21': 'value21'}, 'key1': 'value1', 'key3': [1, 2, 3], '_attachments': [{'sha1': '72ceb09f552b40aeb7f4d80c6e6f96cf3ea60869', 'name': 'tmpTiOLae', 'url': 'fsdb:///72ceb09f552b40aeb7f4d80c6e6f96cf3ea60869', 'notes': '', 'mime': None, 'download_count': 0, 'id': '04879c830d41463d91a54120a74fc7f0', 'size': 10}, {'sha1': '27bc5fea5207e3cac9b42e043433be4161a2beb0', 'name': 'tmp7u9N1R', 'url': 'fsdb:///27bc5fea5207e3cac9b42e043433be4161a2beb0', 'notes': '', 'mime': None, 'download_count': 0, 'id': 'd3d4d3e692504879a3ecd3e7495f0823', 'size': 10}, {'sha1': '188b8b605504ed744a7e42060382e518765b67f2', 'name': 'tmpgoLIts', 'url': 'fsdb:///188b8b605504ed744a7e42060382e518765b67f2', 'notes': '', 'mime': None, 'download_count': 0, 'id': '6fd1eec9d7a34a1dbd166b1bd14eb99a', 'size': 10}]}
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: "HEAD /test-archivant HTTP/1.1" 200 0
elasticsearch: INFO: HEAD http://localhost:9200/test-archivant [status:200 request:0.001s]
elasticsearch: DEBUG: > None
elasticsearch: DEBUG: < 
libreantdb.api: DEBUG: waiting for index "test-archivant" to be ready
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "GET /_cluster/health/test-archivant?wait_for_status=yellow&level=index HTTP/1.1" 200 389
elasticsearch: INFO: GET http://localhost:9200/_cluster/health/test-archivant?wait_for_status=yellow&level=index [status:200 request:0.001s]
elasticsearch: DEBUG: > None
elasticsearch: DEBUG: < {"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":5,"active_shards":5,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":5,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
libreantdb.api: DEBUG: index "test-archivant" is now ready
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "POST /test-archivant/book?op_type=create HTTP/1.1" 201 147
elasticsearch: INFO: POST http://localhost:9200/test-archivant/book?op_type=create [status:201 request:0.035s]
elasticsearch: DEBUG: > {"key3": [1, 2, 3], "key2": {"key22": "value22", "key21": "value21"}, "key1": "value1", "_attachments": [{"sha1": "72ceb09f552b40aeb7f4d80c6e6f96cf3ea60869", "name": "tmpTiOLae", "url": "fsdb:///72ceb09f552b40aeb7f4d80c6e6f96cf3ea60869", "notes": "", "mime": null, "download_count": 0, "id": "04879c830d41463d91a54120a74fc7f0", "size": 10}, {"sha1": "27bc5fea5207e3cac9b42e043433be4161a2beb0", "name": "tmp7u9N1R", "url": "fsdb:///27bc5fea5207e3cac9b42e043433be4161a2beb0", "notes": "", "mime": null, "download_count": 0, "id": "d3d4d3e692504879a3ecd3e7495f0823", "size": 10}, {"sha1": "188b8b605504ed744a7e42060382e518765b67f2", "name": "tmpgoLIts", "url": "fsdb:///188b8b605504ed744a7e42060382e518765b67f2", "notes": "", "mime": null, "download_count": 0, "id": "6fd1eec9d7a34a1dbd166b1bd14eb99a", "size": 10}], "_language": "en", "_text_en": "value22 value21 value1"}
elasticsearch: DEBUG: < {"_index":"test-archivant","_type":"book","_id":"AVNhLLazws--i0ohpzVI","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}
archivant: DEBUG: added new volume: 'AVNhLLazws--i0ohpzVI'
archivant: DEBUG: Deleting volume: 'AVNhLLazws--i0ohpzVI'
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "DELETE /test-archivant/book/AVNhLLazws--i0ohpzVI HTTP/1.1" 200 145
elasticsearch: INFO: DELETE http://localhost:9200/test-archivant/book/AVNhLLazws--i0ohpzVI [status:200 request:0.041s]
elasticsearch: DEBUG: > None
elasticsearch: DEBUG: < {"found":true,"_index":"test-archivant","_type":"book","_id":"AVNhLLazws--i0ohpzVI","_version":2,"_shards":{"total":2,"successful":1,"failed":0}}
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "POST /test-archivant/_refresh HTTP/1.1" 200 50
elasticsearch: INFO: POST http://localhost:9200/test-archivant/_refresh [status:200 request:0.022s]
elasticsearch: DEBUG: > None
elasticsearch: DEBUG: < {"_shards":{"total":10,"successful":5,"failed":0}}
archivant: DEBUG: shrinking local fsdb [danglings=True, corrupted=True]
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "GET /test-archivant/_count HTTP/1.1" 200 59
elasticsearch: INFO: GET http://localhost:9200/test-archivant/_count [status:200 request:0.002s]
elasticsearch: DEBUG: > {"query": {"match": {"_attachments.url": "fsdb:///188b8b605504ed744a7e42060382e518765b67f2"}}}
elasticsearch: DEBUG: < {"count":1,"_shards":{"total":5,"successful":5,"failed":0}}
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "GET /test-archivant/_count HTTP/1.1" 200 59
elasticsearch: INFO: GET http://localhost:9200/test-archivant/_count [status:200 request:0.002s]
elasticsearch: DEBUG: > {"query": {"match": {"_attachments.url": "fsdb:///27bc5fea5207e3cac9b42e043433be4161a2beb0"}}}
elasticsearch: DEBUG: < {"count":1,"_shards":{"total":5,"successful":5,"failed":0}}
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: DEBUG: "GET /test-archivant/_count HTTP/1.1" 200 59
elasticsearch: INFO: GET http://localhost:9200/test-archivant/_count [status:200 request:0.002s]
elasticsearch: DEBUG: > {"query": {"match": {"_attachments.url": "fsdb:///72ceb09f552b40aeb7f4d80c6e6f96cf3ea60869"}}}
elasticsearch: DEBUG: < {"count":1,"_shards":{"total":5,"successful":5,"failed":0}}
--------------------- >> end captured logging << ---------------------

Name                            Stmts   Miss  Cover   Missing
-------------------------------------------------------------
archivant.py                        2      0   100%
archivant/archivant.py            239     22    91%   78, 161, 187, 202, 218, 226-228, 307, 355, 357, 359, 361, 375, 392-395, 398-401
archivant/exceptions.py             4      0   100%
cli.py                              0      0   100%
cli/agherant.py                    35     20    43%   19-38, 41
cli/custom_types.py                 8      1    88%   12
cli/libreant.py                    56     34    39%   26-61, 64
cli/libreant_db.py                 74     45    39%   25-48, 55-63, 69-73, 80-87, 93-95, 99
cli/libreant_users.py             159     74    53%   18-19, 39, 47, 56-60, 67-70, 77-80, 91-101, 108, 117-119, 125-127, 134-139, 145, 150, 156, 162-169, 174, 180-182, 189-193, 200-203, 208, 214, 221-232, 244-249, 255, 260-261
conf.py                             0      0   100%
conf/config_utils.py               52      4    92%   17-19, 92
conf/defaults.py                    9      0   100%
libreantdb.py                       2      0   100%
libreantdb/api.py                 107     21    80%   152, 168-176, 179, 191, 194, 199, 202, 226, 256-261, 285-295
presets.py                          2      0   100%
presets/presetManager.py          136     15    89%   48, 68-69, 74, 79, 88, 91-92, 96-98, 232, 235, 293, 305
users.py                           46      4    91%   116, 126-128
users/api.py                      117     10    91%   31-34, 63-66, 109-110, 155, 159
users/models.py                   107      4    96%   30, 61, 151, 175
utils.py                            0      0   100%
utils/loggers.py                   11      0   100%
webant.py                           2      0   100%
webant/agherant.py                 46     34    26%   18-33, 37-58, 61-65
webant/agherant_standalone.py      19     11    42%   10-20, 24-25, 28
webant/api.py                       0      0   100%
webant/api/archivant_api.py       137    100    27%   21-22, 25-26, 28, 44-53, 58-69, 74-78, 83-87, 92-96, 101-125, 130-134, 139-143, 148-153, 158-161, 165-171, 175-185
webant/api/blueprint_api.py        21      2    90%   33-34
webant/api/users_api.py           180      2    99%   192-193
webant/api/util.py                 18      2    89%   13, 18
webant/constants.py                 1      0   100%
webant/util.py                     64     24    63%   13-16, 37-40, 46-49, 106, 109, 112, 115, 118-121, 124, 127, 133, 139
webant/webant.py                  224    121    46%   76, 100, 104-107, 113-118, 123-167, 175-178, 187-209, 223-236, 244-248, 258-259, 265-267, 271-284, 288-291, 294-297, 301, 309-314, 318-319, 323, 328, 332, 338, 342-343, 346
webant/webserver_utils.py          18     17     6%   7-26
-------------------------------------------------------------
TOTAL                            1896    567    70%
----------------------------------------------------------------------
Ran 232 tests in 11.419s

FAILED (errors=84, failures=2)
```

**Comment by leophys** [comment]
I still don't get I to be of some use with these tests.

**Comment by boyska** [comment]
I think that your investigations are concluding that as of **NOW**, we are **not** supporting elasticsearch `2.x`. We can work to support it, but now we just don't have it.

**Comment by leophys** [comment]
I'm fine with this. My only concern is then to modify the docs to explicitly warn about such issue in arch. I can go on testing in a Debian container.

**Comment by boyska** [comment]
Blallo:
>My only concern is then to modify the docs to explicitly warn about such issue in arch.

please do that

>I can go on testing in a Debian container.

yes, I think that for now that's the only way (or, you could downgrade
your elasticsearch installation on archlinux, which is what I do)

**Comment by ael-code** [comment]
I've a working solution for this. I'm trying to make the change backward-compatible.

**Comment by ael-code** [comment]
Do you know which version of elasticsearch has introduced the incompatibility or at least the last you remember that was working?

**Comment by boyska** [comment]
>Do you know which version of elasticsearch has introduced the incompatibility or at least the last you remember that was working?

1.7 works, 2.0 does not

**Comment by ael-code** [comment]
#281  should fix this
