### ISSUE TITLE
bad error description on read configuration file error

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#283]
##### wrong input configuration file:
```
[{"attachments": [{"url": "fsdb:///4fd434d6ea6841449c00d70ffe28798518957cb0", "type": "attachment", "id": "9136bdff41674e6faa8a41e6c98ec40d", "metadata": {"sha1": "4fd434d6ea6841449c00d70ffe28798518957cb0", "name": "Ashcroft 28 - Sconosciuto.pdf", "notes": "", "mime": null, "download_count": 0, "size": 23695893}}], "score": 0.0, "type": "volume", "id": "AVOBVDXZ20deUdWhI-DC", "metadata": {"tag1": "Ashcroft 28 (22)", "title": "Ashcroft 28 - Sconosciuto", "author": "Sconosciuto", "_language": "it"}}]
```
##### Traceback:
```
Traceback (most recent call last):
  File "/home/libreant/libreant/ve/bin/libreant", line 9, in <module>
    load_entry_point('libreant==0.4', 'console_scripts', 'libreant')()
  File "/home/libreant/libreant/ve/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/libreant/libreant/ve/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/libreant/libreant/ve/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/libreant/libreant/ve/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/libreant/libreant/cli/libreant.py", line 28, in libreant
    conf.update(load_cfg(settings, debug=debug))
  File "/home/libreant/libreant/cli/__init__.py", line 20, in load_cfg
    return load_configs(envvar_prefix, path=path)
  File "/home/libreant/libreant/conf/config_utils.py", line 88, in load_configs
    conf.update(from_file(path))
ValueError: dictionary update sequence element #0 has length 5; 2 is required
```

**Comment by boyska** [comment]
more details, please!

**Comment by ael-code** [comment]
If you choose a wrong configuration file as the one that I've posted, the reported ValueError is raised. We should print a more understandable message.

**Comment by boyska** [comment]
ael:
>If you choose a wrong configuration file as the one that I've posted,
>the reported ValueError is raised. We should print a more
>understandable message.

The one that you posted isn't even a configuration file :)
So I guess that any non-dictionary would give the same error.  Could you
give us a minimal failing sample of your bug? (I guess that ```[]``` is
enough).
