### ISSUE TITLE
ERROR: could not convert timestamp

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#326]
```
[webant] [ERROR] could not convert timestamp
Traceback (most recent call last):
  File "/libreant/libreant/webant/webant.py", line 338, in timepassedformat_filter
    delta = datetime.fromtimestamp(timestamp / 1000) - datetime.now()
  File "/libreant/libreant/.ve/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/runtime.py", line 635, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
UndefinedError: 'dict object' has no attribute '_insertion_date'
```

Yeap I know there are no reproducible steps

**Comment by ael-code** [comment]
I think that has been fixed. I'll close for now.
